jobs:
  test:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Fetch Tools
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Unit Tests
        run: ./build/workflow

name: Test

on:
  schedule:
    - cron: "5 */6 * * *"
